### ISSUE TITLE
Display background text plugin doesn't output variable values

### ISSUE THREAD

**Issue by MaddoScientisto** [pau-tomas/gb-studio-plugins#1]
If I use $variable in the Display background text  plugin it doesn't output that variable in the text, I thought it would but it doesn't

**Comment by pau-tomas** [comment]
Unfortunately autocomplete of variables isn't available for single line textboxes in plugins so you need to use `$xxx$` to render variables, for example `$100` to render variable 100.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/54246642/147884169-ec4a5b77-17ea-46fa-a209-a9807a6bc7ee.png">
