### ISSUE TITLE
Kernel panic occurred with the Printer plugin on GB Studio 3.1.0

### ISSUE THREAD

**Issue by npckc** [pau-tomas/gb-studio-plugins#10]
Hello, I had a kernel panic error occur with the Printer plugin on GB Studio 3.1.0. 

![Screenshot 2022-11-21 170034](https://user-images.githubusercontent.com/50103058/202996251-63b06d2f-b74d-4d0f-a27d-b8da9fd34b25.png)

This was tested on a Game Boy with the GB Printer as well as in the mGBA emulator with the printer emulation.

Here is the the test project with a .gb build that I used with the plugin when I got the kernel panic error. 

[gbprintertest.zip](https://github.com/pau-tomas/gb-studio-plugins/files/10054541/gbprintertest.zip)

**Comment by pau-tomas** [comment]
Fixed in https://github.com/pau-tomas/gb-studio-plugins/commit/8b414f103f17de3bd7087c96fd7ee3c344f5d5b4
