### ISSUE TITLE
Player Fields onGound variable hanging for a bit before beginning to update.

### ISSUE THREAD

**Issue by TommyOliverSays** [pau-tomas/gb-studio-plugins#2]
Running into an issue with the Player Fields plugin.

![gbstudio_test](https://user-images.githubusercontent.com/56774601/150706728-631b6503-adcd-4a39-9a7d-20a370d1868a.gif)
Currently have a test project set up to fire a bullet when the player is in the air, as well as report the status of the "onGound" Bool when start is pressed. As you can see in the attached gif, for the first minute or so, the variable doesn't update, constantly reporting 0 when start is pressed regardless of player status, and fires bullets constantly.

After ~ a minute, it suddenly starts working as expected, the variable updates when checked, and bullets only fire in the air.

On 3.02, on macOS Monterey.

**Comment by pau-tomas** [comment]
Unlikely it's related to the plugin, following up on https://github.com/chrismaltby/gb-studio/issues/1022
